const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
if('IntersectionObserver' in window&&!reduceMotion){document.body.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}
document.getElementById('year').textContent=new Date().getFullYear();
const toggle=document.querySelector('.nav-toggle'),nav=document.getElementById('navigation');toggle.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{toggle.setAttribute('aria-expanded','false');nav.classList.remove('open')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){toggle.setAttribute('aria-expanded','false');nav.classList.remove('open');toggle.focus()}});
document.getElementById('contact-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const text=`Enquiry for Hangover Shakes\nName: ${data.get('name')}\nEmail: ${data.get('email')||'Not provided'}\nPhone: ${data.get('phone')||'Not provided'}\n\n${data.get('message')}`;const url='https://wa.me/917708262499?text='+encodeURIComponent(text);const link=document.getElementById('whatsapp-fallback');link.href=url;link.hidden=false;window.open(url,'_blank','noopener,noreferrer');document.getElementById('form-status').textContent='Your WhatsApp draft is ready. Review it and tap Send in WhatsApp. If it did not open, use the link below.';});
const menuTools=document.querySelector('.menu-tools'),filterButtons=[...document.querySelectorAll('[data-filter]')],menuCards=[...document.querySelectorAll('.product[data-category]')];let activeCategory='all';
function filterMenu(){let count=0;menuCards.forEach(card=>{const show=(activeCategory==='all'||card.dataset.category===activeCategory);card.hidden=!show;if(show){count++;card.classList.add('visible')}});document.getElementById('menu-count').textContent=`${count} of ${menuCards.length} menu highlights`;document.querySelector('.menu-empty').hidden=count>0;}
menuTools.hidden=false;filterButtons.forEach(button=>button.addEventListener('click',()=>{activeCategory=button.dataset.filter;filterButtons.forEach(item=>item.setAttribute('aria-pressed',String(item===button)));filterMenu()}));document.getElementById('reset-menu').addEventListener('click',()=>{activeCategory='all';filterButtons.forEach(item=>item.setAttribute('aria-pressed',String(item.dataset.filter==='all')));filterMenu();filterButtons[0].focus()});filterMenu();
document.querySelectorAll('[data-enquiry]').forEach(link=>link.addEventListener('click',()=>{const message=document.querySelector('textarea[name=message]');if(!message.value.trim())message.value=link.dataset.enquiry;}));
